# Generated by Django 6.1.1 on 2026-09-29 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorName', models.CharField(max_length=100)),
                ('Hospital', models.CharField(max_length=100)),
                ('visitDate', models.DateField()),
                ('Reason', models.TextField(blank=True)),
                ('Diagnosis', models.TextField(blank=True)),
                ('Prescription', models.TextField(blank=True)),
                ('Notes', models.TextField(blank=True)),
                ('Result', models.FileField(blank=True, upload_to='result/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
